apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: development

resources:
  - ../../base
  - dragonfly.yaml

configMapGenerator:
  - name: course-app-config-map
    literals:
      - APP_STORE=redis
      - APP_REDIS_URL=redis://dragonfly.development:6379/0
      - APP_MESSAGE=Hello World
